### ISSUE TITLE
`link` specification incompatibility error with `fedtest` command

### ISSUE THREAD

**Issue by ardatan** [apollographql/apollo-federation-subgraph-compatibility#358]
`fedtest` CLI creates `supergraph.graphql` with `@link(url: "https://specs.apollo.dev/join/v0.3", for: EXECUTION)` 
Then `router` fails with `Invalid supergraph: uses unsupported join spec version v0.3 (supported versions: v0.2, v0.1`.

https://github.com/dotansimha/graphql-yoga/actions/runs/4173140505/jobs/7225119764#step:8:312

Rover version; [v0.11.1](https://rover.apollo.dev/nix/v0.11.1)
`@apollo/federation-subgraph-compatibility` version; 1.0.1

The command I use;
`fedtest docker --compose ./docker-compose.yaml --schema ./schema.graphql --path /graphql --port 4001 --debug --format markdown` -> https://github.com/dotansimha/graphql-yoga/pull/2436/files#diff-2a8444e25a7fde00cf23c11069f3ea869362685cd4918bfbe980c1522d340e52R12

**Comment by dariuszkuc** [comment]
Hello 👋 
Thanks for raising this. In order to avoid those breaking changes in the future, I've pinned composition version within the script itself (see https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/353). I've released [v1.1.0](https://github.com/apollographql/apollo-federation-subgraph-compatibility/releases/tag/1.1.0) with the changes.

Thanks,
Derek

**Comment by ardatan** [comment]
Thank you for the fix!
But now it says `No tests found`.
https://github.com/dotansimha/graphql-yoga/actions/runs/4181145613/jobs/7242805471#step:8:364

**Comment by dariuszkuc** [comment]
@ardatan That is odd. Tests should be [there](https://www.npmjs.com/package/@apollo/federation-subgraph-compatibility-tests?activeTab=explore)

```
In /home/runner/work/graphql-yoga/graphql-yoga/node_modules/.pnpm/@apollo+federation-subgraph-compatibility-tests@1.1.0_wyaqim46cuthwo3oxpq6pvkvb4/node_modules/@apollo/federation-subgraph-compatibility-tests
  93 files checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 24 matches
  testPathIgnorePatterns:  - 0 matches
  testRegex:  - 0 matches
Pattern: /home/runner/work/graphql-yoga/graphql-yoga/node_modules/.pnpm/@apollo+federation-subgraph-compatibility-tests@1.1.0_wyaqim46cuthwo3oxpq6pvkvb4/node_modules/@apollo/federation-subgraph-compatibility-tests/dist/tests - 0 matches
```

Based on the above it finds 24 matches using `testMatch` pattern (there are 12 test files which gets compiled to the corresponding `*.test.d.ts` and `*.test.js` files) but then it complains that it didn't find any tests under `dist/tests`. I'm confused - can you try it locally? Maybe it is something due to environment?

Latest release seems to work fine in [federation-jvm](https://github.com/apollographql/federation-jvm/pull/294) and [graphql-kotlin](https://github.com/ExpediaGroup/graphql-kotlin/pull/1661)
